import "dotenv/config";

export const ENV = {
  PORT: process.env.PORT,
  MONGODB_URI: process.env.MONGODB_URI,

  ACCESS_TOKEN_SECRET_KEY: process.env.ACCESS_TOKEN_SECRET_KEY,
  ACCESS_TOKEN_SECRET_EXPIRED: process.env.ACCESS_TOKEN_SECRET_EXPIRED,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_EXPIRED: process.env.REFRESH_TOKEN_SECRET_EXPIRED,
};
